2019-12-16 11:24:14	[INFO]	Traceback (most recent call last):
  File "E:/python_test/python/day21/homework/core/autohome.py", line 36, in <module>
    src = img.get("src")
AttributeError: 'NoneType' object has no attribute 'get'

2019-12-16 11:24:42 - root - ERROR -log:  E:/python_test/python/day21/homework/core/autohome.py line40 error!
Traceback (most recent call last):
  File "E:/python_test/python/day21/homework/core/autohome.py", line 36, in <module>
    src = img.get("src")
AttributeError: 'NoneType' object has no attribute 'get'

